version: '3.8'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    env_file:
      - ./config/.env

  redis:
    image: redis:6.2-alpine
    restart: unless-stopped
    depends_on:
      - db

  celery:
    build: .
    restart: always
    command: celery -A config worker -l info
    depends_on:
      - redis

  backend:
    build: .
    restart: always
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - celery
    env_file:
      - ./config/.env
