# Generated by Django 4.2.3 on 2023-07-28 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                ("client_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "phone_number",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Phone number must start with 7 and have a length of 11 digits.",
                                regex="^7\\d{10}$",
                            )
                        ],
                    ),
                ),
                ("operator_code", models.CharField(max_length=3)),
                ("tag", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Client",
                "verbose_name_plural": "Clients",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("mailing_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "start_datetime",
                    models.DateTimeField(verbose_name="Date and time of mailing start"),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(verbose_name="Date and time of mailing end"),
                ),
                ("filter", models.CharField(max_length=100, verbose_name="Filter")),
            ],
            options={
                "verbose_name": "Mailing",
                "verbose_name_plural": "Mailings",
            },
        ),
    ]
